In [2]:
!pip install datasets

ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 324, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/index_command.py", line 71, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/index_command.py", line 100, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/network/session.py", line 344, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/network/session.py", line 177, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 186, in <genexpr>
    for distribution in self.iter_all_distributions()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 177, in _iter_distributions
    for dist in finder.find_eggs(location):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 113, in _find_eggs_in_dir
    from pip._internal.metadata import pkg_resources as legacy
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 946, in _load_unlocked
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1030, in handle
    self.release()
  File "/usr/lib/python3.12/logging/__init__.py", line 975, in release
    def release(self):

KeyboardInterrupt
^C

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [3]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg.notna())]

       job_title_short  ...                                    job_type_skills
109       Data Analyst  ...  {'analyst_tools': ['alteryx', 'tableau'], 'pro...
180       Data Analyst  ...         {'analyst_tools': ['excel', 'powerpoint']}
410       Data Analyst  ...  {'analyst_tools': ['word', 'excel', 'visio', '...
988       Data Analyst  ...  {'analyst_tools': ['excel', 'tableau'], 'progr...
1413      Data Analyst  ...  {'analyst_tools': ['excel', 'power bi'], 'prog...
...                ...  ...                                                ...
784033    Data Analyst  ...         {'analyst_tools': ['power bi', 'tableau']}
784423    Data Analyst  ...         {'analyst_tools': ['tableau', 'power bi']}
784882    Data Analyst  ...  {'analyst_tools': ['tableau', 'excel', 'altery...
785187    Data Analyst  ...  {'analyst_tools': ['looker'], 'programming': [...
785515    Data Analyst  ...                                               None

[5451 rows x 17 columns]

In [ ]:

df.iloc[2]  #gets the 2nd row

df['job_country'].unique()


filtered_df = df[df['job_schedule_type'] == 'Full-time']
filtered_df.head(3)

not_na_values_df = df[df['job_skills'].notna()]
not_na_values_df

          job_title_short  ...                                    job_type_skills
1            Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2           Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3           Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4           Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
5           Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...
...                   ...  ...                                                ...
785736  Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737       Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738   Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739      Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740  Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[668704 rows x 17 columns]

In [4]:
df['job_posted_date']=pd.to_datetime(df.job_posted_date)   #conversion to datetime

In [ ]:
df.job_posted_date.dt.month           #takes out month
df['job_posted_month'] = df.job_posted_date.dt.month           #takes out month

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

In [ ]:
df.sort_values('job_posted_date')

df.sort_values('job_posted_date', inplace=True)              #inplace can pernamently remove or change

df.drop(labels = 'salary_hour_avg', axis = 1, inplace = True)      #dropping the column

df.dropna(subset=['salary_year_avg'], inplace = True)

KeyError: "['salary_hour_avg'] not found in axis"

In [ ]:
df.sort_values('salary_year_avg', ascending=False,inplace=True)
df.head(10)

df['job_posted_date']= pd.to_datetime(df['job_posted_date'])
df['job_posted_year'] = df.job_posted_date.dt.year

df.dropna(subset=['salary_year_avg'], inplace=True)

In [29]:
df.describe()
df.info()
df.count()
df['salary_year_avg'].median()
df['salary_year_avg'].min()

min_salary = df['salary_year_avg'].idxmin()  #provide the index value/row number of the minimum salary
df.iloc[min_salary]


df['job_title_short'].unique()
df['job_title_short'].value_counts()

df.groupby('job_title_short')['salary_year_avg'].min()    #First part groups, second part specify what columns we want to do the aggregation of a stat on

df.groupby(['job_title_short','job_country'])['salary_year_avg'].min()     #then groups by country too. <Make sure the things that you are grouping is wihtin a list

df.groupby('job_title_short')[['salary_year_avg','salary_hour_avg']].min()  # Then add in more columns in the 2nd part (Dont forget to put those into lists too)

df.groupby('job_title_short')[['salary_year_avg','salary_hour_avg']].agg(['min','max','median'])  # Multuiple operations/aggregation methods on it. (Dont forget to put those into lists too)

                          salary_year_avg                     salary_hour_avg  \
                                      min       max    median             min
job_title_short
Business Analyst                  16500.0  387460.0   85000.0          10.835
Cloud Engineer                    42000.0  280000.0   90000.0          18.500
Data Analyst                      25000.0  650000.0   90000.0           8.000
Data Engineer                     15000.0  525000.0  125000.0           8.000
Data Scientist                    27000.0  960000.0  127500.0           8.000
Machine Learning Engineer         30000.0  325000.0  106415.0          10.000
Senior Data Analyst               30000.0  425000.0  111175.0          13.000
Senior Data Engineer              35000.0  425000.0  147500.0          12.500
Senior Data Scientist             45000.0  890000.0  155500.0          17.500
Software Engineer                 28000.0  375000.0   99150.0          11.000


                             max     median
job_title_short
Business Analyst           132.5  40.362499
Cloud Engineer              91.0  40.000000
Data Analyst               391.0  32.615002
Data Engineer              184.5  58.500000
Data Scientist             237.5  47.500000
Machine Learning Engineer   87.5  47.535000
Senior Data Analyst        130.0  47.500000
Senior Data Engineer       170.0  61.500000
Senior Data Scientist      150.0  47.620003
Software Engineer          102.5  47.560001

In [47]:
print(df['salary_year_avg'].mean())
print(df['salary_year_avg'].median())

df.groupby('job_title_short')['salary_hour_avg'].mean()    #General way to groupby

min_hourly_index = df['salary_hour_avg'].idxmin()
df.iloc[min_hourly_index][['job_title_short','salary_hour_avg']]     #gets index and then returns specific coloumns


df.groupby('job_country').size()   #Just returns the count

job_country
Afghanistan      16
Albania         119
Algeria         111
Angola           11
Argentina      8736
               ...
Venezuela        69
Vietnam        2414
Yemen            10
Zambia          104
Zimbabwe         81
Length: 160, dtype: int64

In [49]:
# Exercise

SyntaxError: invalid syntax (3320819389.py, line 1)

In [67]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date']=pd.to_datetime(df.job_posted_date)


df['job_country'].value_counts().head(20)

df['job_country'].isin(['Brazil']).any()   #see if Brazil is in the dataset

us_jobs = df[df['job_country'] == "United States"]            #create a new dataframe that filers to a country of choice

us_jobs = us_jobs[us_jobs['salary_year_avg'].notna()]            #More filters to include data without NAN

us_jobs

us_jobs.groupby('job_title_short').count()  #Group by job title and gets count of every. Min wont work

us_jobs.groupby('job_title_short')['salary_year_avg'].min()

us_jobs.groupby('job_title_short')['salary_year_avg'].agg('median')

us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['min','median','max','count'])   #For more aggregations, put them into a list

us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median','min','max','count']).sort_values(by = 'median', ascending = False)   #Sort by median, descending

                             median      min       max  count
job_title_short
Senior Data Scientist      155000.0  55000.0  475000.0   1241
Machine Learning Engineer  150000.0  44408.5  315000.0    128
Senior Data Engineer       150000.0  45000.0  375000.0   1058
Data Scientist             130000.0  30000.0  960000.0   4553
Software Engineer          130000.0  48982.0  375000.0    157
Data Engineer              125000.0  23496.0  525000.0   2915
Cloud Engineer             116100.0  42000.0  221844.0     20
Senior Data Analyst        110000.0  35360.0  425000.0    913
Business Analyst            90000.0  35000.0  387460.0    431
Data Analyst                90000.0  25000.0  375000.0   4350